// Predefined quotation templates, keyed by business category.
//
// This module is the single source of truth for starter template content —
// no template copy or field lists should be hardcoded inside components.
// Each starter template pre-populates fixed content, prompt fields, and
// suggested line items; the user customizes and saves their own copy from
// there (see src/routes/_authenticated/onboarding.tsx).
import {
  Heart,
  Camera,
  Megaphone,
  PartyPopper,
  Clapperboard,
  Briefcase,
  Package,
  LayoutTemplate,
  type LucideIcon,
} from "lucide-react";
import type {
  TemplateFieldDraft,
  TemplateLineItemDraft,
  TemplateFixedContent,
} from "./template-types";

export type BusinessCategoryId =
  | "wedding_photography"
  | "general_photography"
  | "marketing_agency"
  | "event_management"
  | "video_production"
  | "freelancer_consultant"
  | "product_supplier"
  | "custom_blank";

export interface StarterTemplate {
  id: BusinessCategoryId;
  categoryLabel: string; // stored on businesses.category
  name: string; // default template name
  description: string; // shown on the selection card
  icon: LucideIcon;
  fixedContent: TemplateFixedContent;
  fields: TemplateFieldDraft[];
  lineItems: TemplateLineItemDraft[];
}

const CORE_FIELDS: TemplateFieldDraft[] = [
  {
    key: "quotation_date",
    label: "Quotation date",
    field_type: "date",
    category: "variable",
    required: true,
  },
  {
    key: "valid_until_days",
    label: "Quotation valid for (days)",
    field_type: "number",
    category: "variable",
    required: true,
    default_value: 15,
  },
];

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: "wedding_photography",
    categoryLabel: "Wedding photography",
    name: "Wedding Photography Quotation",
    description: "Couple details, events, deliverables, and crew for wedding shoots.",
    icon: Heart,
    fixedContent: {
      company_intro:
        "We create timeless wedding photography and films that capture every emotion of your big day.",
      terms:
        "Quotation is valid for the period stated above. Final pricing may vary based on confirmed dates, guest count, and selected add-ons. Copyright of all images and films remains with the studio; clients receive a personal-use license.",
      payment_terms: "50% advance to confirm the date, 30% before the event, 20% on delivery.",
      bank_details: "",
      footer: "Thank you for considering us for your wedding.",
      notes: "Prices may vary based on final guest count and add-ons selected.",
    },
    fields: [
      {
        key: "couple_names",
        label: "Couple's names",
        field_type: "short_text",
        category: "variable",
        required: true,
        example_value: "Aman & Priya",
      },
      {
        key: "wedding_date",
        label: "Wedding date",
        field_type: "date",
        category: "variable",
        required: true,
      },
      {
        key: "additional_event_dates",
        label: "Other event dates",
        field_type: "long_text",
        category: "optional",
        required: false,
        help_text: "Mehendi, sangeet, reception, etc.",
      },
      {
        key: "venue",
        label: "Venue",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "city",
        label: "City",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "event_list",
        label: "Events covered",
        field_type: "long_text",
        category: "variable",
        required: false,
        example_value: "Mehendi, Sangeet, Wedding, Reception",
      },
      {
        key: "photography_services",
        label: "Photography services",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      {
        key: "cinematography_services",
        label: "Cinematography services",
        field_type: "long_text",
        category: "optional",
        required: false,
      },
      {
        key: "team_size",
        label: "Team size",
        field_type: "number",
        category: "variable",
        required: false,
        help_text: "Photographers + videographers on the day",
      },
      {
        key: "deliverables",
        label: "Deliverables",
        field_type: "long_text",
        category: "variable",
        required: true,
        example_value: "500+ edited photos, 1 wedding film, 1 photobook",
      },
      {
        key: "edited_photo_count",
        label: "Edited photographs",
        field_type: "number",
        category: "optional",
        required: false,
      },
      {
        key: "wedding_film_duration",
        label: "Wedding film duration",
        field_type: "short_text",
        category: "optional",
        required: false,
        example_value: "4-6 minutes",
      },
      {
        key: "reels_count",
        label: "Reels / highlight videos",
        field_type: "number",
        category: "optional",
        required: false,
      },
      {
        key: "photobook_included",
        label: "Photobook included",
        field_type: "boolean",
        category: "optional",
        required: false,
      },
      {
        key: "logistics_notes",
        label: "Logistics notes",
        field_type: "long_text",
        category: "optional",
        required: false,
      },
      {
        key: "accommodation_required",
        label: "Accommodation required for team",
        field_type: "boolean",
        category: "optional",
        required: false,
      },
      {
        key: "travel_required",
        label: "Travel required for team",
        field_type: "boolean",
        category: "optional",
        required: false,
      },
      {
        key: "payment_schedule",
        label: "Payment schedule",
        field_type: "long_text",
        category: "variable",
        required: true,
        example_value: "50% advance, 30% before event, 20% on delivery",
      },
      {
        key: "delivery_timeline",
        label: "Delivery timeline",
        field_type: "short_text",
        category: "variable",
        required: true,
        example_value: "4-6 weeks after the event",
      },
      {
        key: "revision_policy",
        label: "Revision policy",
        field_type: "long_text",
        category: "optional",
        required: false,
      },
      ...CORE_FIELDS,
    ],
    lineItems: [
      { name: "Candid photography", unit: "event" },
      { name: "Traditional photography", unit: "event" },
      { name: "Wedding cinematography", unit: "event" },
      { name: "Traditional videography", unit: "event" },
      { name: "Drone coverage", unit: "event" },
      { name: "Same-day edit", unit: "event" },
      { name: "Wedding film", unit: "package" },
      { name: "Social media reels", unit: "package" },
      { name: "Photobooks", unit: "unit" },
      { name: "Travel", unit: "trip" },
      { name: "Accommodation", unit: "night" },
      { name: "Additional crew", unit: "person" },
    ],
  },
  {
    id: "general_photography",
    categoryLabel: "General photography",
    name: "Photography Quotation",
    description: "Portraits, products, real estate, or events — a flexible shoot quote.",
    icon: Camera,
    fixedContent: {
      company_intro: "Professional photography tailored to your shoot, on your schedule.",
      terms:
        "Quotation valid for the period stated above. Rescheduling within 48 hours may incur a fee.",
      payment_terms: "50% advance to confirm booking, balance due on delivery.",
      bank_details: "",
      footer: "Thank you for the opportunity to work with you.",
      notes: "Final pricing may vary based on shoot duration and location.",
    },
    fields: [
      {
        key: "client_name",
        label: "Client name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "shoot_type",
        label: "Shoot type",
        field_type: "dropdown",
        category: "variable",
        required: true,
        options: ["Portrait", "Product", "Event", "Real estate", "Other"],
      },
      {
        key: "shoot_date",
        label: "Shoot date",
        field_type: "date",
        category: "variable",
        required: true,
      },
      {
        key: "location",
        label: "Location",
        field_type: "short_text",
        category: "variable",
        required: false,
      },
      {
        key: "team_size",
        label: "Team size",
        field_type: "number",
        category: "optional",
        required: false,
      },
      {
        key: "deliverables",
        label: "Deliverables",
        field_type: "long_text",
        category: "variable",
        required: true,
        example_value: "50 edited photos, high-resolution files",
      },
      {
        key: "edited_photo_count",
        label: "Edited photographs",
        field_type: "number",
        category: "optional",
        required: false,
      },
      {
        key: "turnaround_time",
        label: "Turnaround time",
        field_type: "short_text",
        category: "variable",
        required: false,
        example_value: "2 weeks",
      },
      {
        key: "usage_rights",
        label: "Usage rights",
        field_type: "long_text",
        category: "optional",
        required: false,
      },
      ...CORE_FIELDS,
    ],
    lineItems: [
      { name: "Photography session", unit: "session" },
      { name: "Additional hour", unit: "hour" },
      { name: "Retouching", unit: "photo" },
      { name: "Prints", unit: "unit" },
      { name: "Extended licensing", unit: "license" },
    ],
  },
  {
    id: "marketing_agency",
    categoryLabel: "Marketing agency",
    name: "Marketing Services Quotation",
    description: "Scope, channels, and deliverables for a marketing engagement.",
    icon: Megaphone,
    fixedContent: {
      company_intro: "We help brands grow with strategy-led marketing across every channel.",
      terms: "Quotation valid for the period stated above. Scope changes may be quoted separately.",
      payment_terms: "Monthly retainer billed in advance, or 50% upfront for fixed-scope projects.",
      bank_details: "",
      footer: "Looking forward to growing your brand together.",
      notes: "Ad spend is billed separately from management fees unless stated otherwise.",
    },
    fields: [
      {
        key: "client_name",
        label: "Client name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "company_name",
        label: "Company name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "project_name",
        label: "Project / campaign name",
        field_type: "short_text",
        category: "variable",
        required: false,
      },
      {
        key: "scope_of_work",
        label: "Scope of work",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      {
        key: "campaign_duration",
        label: "Campaign duration",
        field_type: "short_text",
        category: "variable",
        required: false,
        example_value: "3 months",
      },
      {
        key: "channels",
        label: "Channels",
        field_type: "long_text",
        category: "variable",
        required: false,
        example_value: "Instagram, Google Ads, Email",
      },
      {
        key: "deliverables",
        label: "Deliverables",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      {
        key: "reporting_frequency",
        label: "Reporting frequency",
        field_type: "dropdown",
        category: "optional",
        required: false,
        options: ["Weekly", "Biweekly", "Monthly"],
      },
      {
        key: "payment_schedule",
        label: "Payment schedule",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      ...CORE_FIELDS,
    ],
    lineItems: [
      { name: "Strategy & planning", unit: "package" },
      { name: "Social media management", unit: "month" },
      { name: "Content creation", unit: "month" },
      { name: "Paid ads management", unit: "month" },
      { name: "SEO", unit: "month" },
      { name: "Analytics & reporting", unit: "month" },
    ],
  },
  {
    id: "event_management",
    categoryLabel: "Event management",
    name: "Event Management Quotation",
    description: "Planning, vendors, and on-the-day coordination for any event.",
    icon: PartyPopper,
    fixedContent: {
      company_intro: "Full-service event planning and coordination, start to finish.",
      terms:
        "Quotation valid for the period stated above. Vendor costs are estimates until confirmed.",
      payment_terms: "40% advance to confirm, 40% one month prior, 20% on the event day.",
      bank_details: "",
      footer: "Thank you for trusting us with your event.",
      notes: "Final pricing may vary based on confirmed guest count and vendor selections.",
    },
    fields: [
      {
        key: "client_name",
        label: "Client name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "event_type",
        label: "Event type",
        field_type: "dropdown",
        category: "variable",
        required: true,
        options: ["Wedding", "Corporate", "Birthday", "Concert", "Other"],
      },
      {
        key: "event_date",
        label: "Event date",
        field_type: "date",
        category: "variable",
        required: true,
      },
      {
        key: "venue",
        label: "Venue",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "guest_count",
        label: "Guest count",
        field_type: "number",
        category: "variable",
        required: false,
      },
      {
        key: "services_included",
        label: "Services included",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      {
        key: "vendors_coordinated",
        label: "Vendors coordinated",
        field_type: "long_text",
        category: "optional",
        required: false,
      },
      {
        key: "setup_teardown",
        label: "Setup & teardown included",
        field_type: "boolean",
        category: "optional",
        required: false,
      },
      {
        key: "payment_schedule",
        label: "Payment schedule",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      ...CORE_FIELDS,
    ],
    lineItems: [
      { name: "Event planning & coordination", unit: "event" },
      { name: "Venue decor", unit: "event" },
      { name: "Catering coordination", unit: "guest" },
      { name: "Sound & lighting", unit: "event" },
      { name: "Entertainment", unit: "event" },
      { name: "On-site staffing", unit: "person" },
    ],
  },
  {
    id: "video_production",
    categoryLabel: "Video production",
    name: "Video Production Quotation",
    description: "Shoot days, crew, and deliverables for a video project.",
    icon: Clapperboard,
    fixedContent: {
      company_intro: "We produce polished video content, from concept to final cut.",
      terms:
        "Quotation valid for the period stated above. Additional revision rounds may be billed separately.",
      payment_terms: "50% advance to begin production, balance due on final delivery.",
      bank_details: "",
      footer: "Thank you for considering us for your project.",
      notes: "Licensed music and stock footage are billed at cost unless included above.",
    },
    fields: [
      {
        key: "client_name",
        label: "Client name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "project_title",
        label: "Project title",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "video_type",
        label: "Video type",
        field_type: "dropdown",
        category: "variable",
        required: true,
        options: ["Corporate", "Advertisement", "Music video", "Documentary", "Other"],
      },
      {
        key: "shoot_days",
        label: "Shoot days",
        field_type: "number",
        category: "variable",
        required: false,
      },
      {
        key: "crew_size",
        label: "Crew size",
        field_type: "number",
        category: "optional",
        required: false,
      },
      {
        key: "deliverables",
        label: "Deliverables",
        field_type: "long_text",
        category: "variable",
        required: true,
        example_value: "1 final cut, 3 social edits",
      },
      {
        key: "edited_duration",
        label: "Edited duration",
        field_type: "short_text",
        category: "optional",
        required: false,
        example_value: "3-5 minutes",
      },
      {
        key: "revision_rounds",
        label: "Revision rounds included",
        field_type: "number",
        category: "optional",
        required: false,
      },
      {
        key: "delivery_timeline",
        label: "Delivery timeline",
        field_type: "short_text",
        category: "variable",
        required: false,
        example_value: "3-4 weeks after shoot",
      },
      ...CORE_FIELDS,
    ],
    lineItems: [
      { name: "Pre-production & scripting", unit: "project" },
      { name: "Filming day", unit: "day" },
      { name: "Editing", unit: "project" },
      { name: "Motion graphics", unit: "project" },
      { name: "Drone footage", unit: "day" },
      { name: "Licensed music", unit: "track" },
    ],
  },
  {
    id: "freelancer_consultant",
    categoryLabel: "Freelancer / consultant",
    name: "Freelance Services Quotation",
    description: "Scope, engagement type, and timeline for independent work.",
    icon: Briefcase,
    fixedContent: {
      company_intro: "Independent, focused work delivered on your timeline.",
      terms:
        "Quotation valid for the period stated above. Scope changes may affect pricing and timeline.",
      payment_terms: "50% advance for fixed-scope projects, or monthly billing for retainers.",
      bank_details: "",
      footer: "Thank you for the opportunity to work together.",
      notes: "Hourly estimates are approximate and billed based on actual time logged.",
    },
    fields: [
      {
        key: "client_name",
        label: "Client name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "project_name",
        label: "Project name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "scope_of_work",
        label: "Scope of work",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      {
        key: "engagement_type",
        label: "Engagement type",
        field_type: "dropdown",
        category: "variable",
        required: true,
        options: ["Hourly", "Fixed price", "Retainer"],
      },
      {
        key: "estimated_hours",
        label: "Estimated hours",
        field_type: "number",
        category: "optional",
        required: false,
      },
      {
        key: "start_date",
        label: "Start date",
        field_type: "date",
        category: "variable",
        required: false,
      },
      {
        key: "delivery_timeline",
        label: "Delivery timeline",
        field_type: "short_text",
        category: "variable",
        required: false,
      },
      {
        key: "payment_schedule",
        label: "Payment schedule",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      ...CORE_FIELDS,
    ],
    lineItems: [
      { name: "Initial consultation", unit: "session" },
      { name: "Project work", unit: "hour" },
      { name: "Revisions", unit: "round" },
      { name: "Monthly retainer", unit: "month" },
    ],
  },
  {
    id: "product_supplier",
    categoryLabel: "Product supplier",
    name: "Product Supply Quotation",
    description: "Unit pricing, quantities, and delivery for product orders.",
    icon: Package,
    fixedContent: {
      company_intro: "Reliable product supply with transparent pricing.",
      terms:
        "Quotation valid for the period stated above. Prices exclude taxes and duties unless stated.",
      payment_terms: "50% advance on order confirmation, balance due before dispatch.",
      bank_details: "",
      footer: "Thank you for your business.",
      notes: "Bulk pricing available on request for larger order quantities.",
    },
    fields: [
      {
        key: "client_name",
        label: "Client name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      {
        key: "company_name",
        label: "Company name",
        field_type: "short_text",
        category: "variable",
        required: false,
      },
      {
        key: "order_reference",
        label: "Order reference",
        field_type: "short_text",
        category: "optional",
        required: false,
      },
      {
        key: "delivery_address",
        label: "Delivery address",
        field_type: "long_text",
        category: "variable",
        required: true,
      },
      {
        key: "delivery_timeline",
        label: "Delivery timeline",
        field_type: "short_text",
        category: "variable",
        required: false,
        example_value: "7-10 business days",
      },
      {
        key: "minimum_order_qty",
        label: "Minimum order quantity",
        field_type: "number",
        category: "optional",
        required: false,
      },
      {
        key: "warranty_info",
        label: "Warranty information",
        field_type: "long_text",
        category: "optional",
        required: false,
      },
      ...CORE_FIELDS,
    ],
    lineItems: [
      { name: "Product unit price", unit: "unit" },
      { name: "Bulk discount tier", unit: "order" },
      { name: "Shipping & handling", unit: "order" },
      { name: "Packaging", unit: "order" },
      { name: "Installation", unit: "visit" },
    ],
  },
  {
    id: "custom_blank",
    categoryLabel: "Custom",
    name: "New template",
    description: "Start from scratch and build the exact structure you need.",
    icon: LayoutTemplate,
    fixedContent: {},
    fields: [
      {
        key: "client_name",
        label: "Client name",
        field_type: "short_text",
        category: "variable",
        required: true,
      },
      ...CORE_FIELDS,
    ],
    lineItems: [],
  },
];

export function getStarterTemplate(id: BusinessCategoryId): StarterTemplate {
  return (
    STARTER_TEMPLATES.find((t) => t.id === id) ?? STARTER_TEMPLATES[STARTER_TEMPLATES.length - 1]
  );
}
