/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedRateCardRouteImport } from './routes/_authenticated/rate-card'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedQuotationsIdRouteImport } from './routes/_authenticated/quotations.$id'
import { Route as AuthenticatedQuotationsNewRouteImport } from './routes/_authenticated/quotations.new'
import { Route as AuthenticatedTemplatesIdRouteImport } from './routes/_authenticated/templates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRateCardRoute = AuthenticatedRateCardRouteImport.update({
  id: '/rate-card',
  path: '/rate-card',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsIdRoute =
  AuthenticatedQuotationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedQuotationsRoute,
  } as any)
const AuthenticatedQuotationsNewRoute =
  AuthenticatedQuotationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedQuotationsRoute,
  } as any)
const AuthenticatedTemplatesIdRoute =
  AuthenticatedTemplatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTemplatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/rate-card': typeof AuthenticatedRateCardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/rate-card': typeof AuthenticatedRateCardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/_authenticated/rate-card': typeof AuthenticatedRateCardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/_authenticated/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/_authenticated/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/_authenticated/templates/$id': typeof AuthenticatedTemplatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/onboarding'
    | '/quotations'
    | '/rate-card'
    | '/settings'
    | '/templates'
    | '/quotations/$id'
    | '/quotations/new'
    | '/templates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/onboarding'
    | '/quotations'
    | '/rate-card'
    | '/settings'
    | '/templates'
    | '/quotations/$id'
    | '/quotations/new'
    | '/templates/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/quotations'
    | '/_authenticated/rate-card'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/quotations/$id'
    | '/_authenticated/quotations/new'
    | '/_authenticated/templates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rate-card': {
      id: '/_authenticated/rate-card'
      path: '/rate-card'
      fullPath: '/rate-card'
      preLoaderRoute: typeof AuthenticatedRateCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$id': {
      id: '/_authenticated/quotations/$id'
      path: '/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AuthenticatedQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedQuotationsRoute
    }
    '/_authenticated/quotations/new': {
      id: '/_authenticated/quotations/new'
      path: '/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AuthenticatedQuotationsNewRouteImport
      parentRoute: typeof AuthenticatedQuotationsRoute
    }
    '/_authenticated/templates/$id': {
      id: '/_authenticated/templates/$id'
      path: '/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AuthenticatedTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedTemplatesRoute
    }
  }
}

interface AuthenticatedQuotationsRouteChildren {
  AuthenticatedQuotationsIdRoute: typeof AuthenticatedQuotationsIdRoute
  AuthenticatedQuotationsNewRoute: typeof AuthenticatedQuotationsNewRoute
}

const AuthenticatedQuotationsRouteChildren: AuthenticatedQuotationsRouteChildren =
  {
    AuthenticatedQuotationsIdRoute: AuthenticatedQuotationsIdRoute,
    AuthenticatedQuotationsNewRoute: AuthenticatedQuotationsNewRoute,
  }

const AuthenticatedQuotationsRouteWithChildren =
  AuthenticatedQuotationsRoute._addFileChildren(
    AuthenticatedQuotationsRouteChildren,
  )

interface AuthenticatedTemplatesRouteChildren {
  AuthenticatedTemplatesIdRoute: typeof AuthenticatedTemplatesIdRoute
}

const AuthenticatedTemplatesRouteChildren: AuthenticatedTemplatesRouteChildren =
  {
    AuthenticatedTemplatesIdRoute: AuthenticatedTemplatesIdRoute,
  }

const AuthenticatedTemplatesRouteWithChildren =
  AuthenticatedTemplatesRoute._addFileChildren(
    AuthenticatedTemplatesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRouteWithChildren
  AuthenticatedRateCardRoute: typeof AuthenticatedRateCardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRouteWithChildren,
  AuthenticatedRateCardRoute: AuthenticatedRateCardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
